---
title: "SAP Analysis"
author: "Monika Lind"
date: "2/26/2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library}
library(tidyverse)
library(rio)
library(here)
library(sjPlot)
library(colorblindr)
library(psych)
```

```{r import}
d1 <- rio::import(here::here("Lind_GS_F17.csv"), setclass = "tbl_df") %>% 
  characterize()

names(d1) <- str_replace_all(names(d1), c("[.]" = "_", "Q" = "q"))

d2 <- rio::import(here::here("Lind_GS_F18.csv"), setclass = "tbl_df") %>% 
  characterize()

names(d2) <- str_replace_all(names(d2), c("[.]" = "_", "Q" = "q"))
```

```{r tidy}
d1_raw <- d1 %>%
  mutate(pid = row_number(),
         group = 1) %>% 
  select(115:116, 3:4, 7:114) %>% 
  rename(date = RecordedDate,
         duration = Duration__in_seconds_,
         race_ethn = q1_3,
         gender = q346,
         gender_text = q346_4_TEXT,
         age = q348) %>% 
  mutate(age = (age + 15)) %>% 
  select(-7)

d2_raw <- d2 %>%
  mutate(pid = (row_number() + 437)) %>% 
  select(119, everything()) %>% 
  rename(date = RecordedDate,
         duration = Duration__in_seconds_,
         race_ethn = q6,
         gender = q62,
         gender_text = q62_4_TEXT,
         age = q63) %>% 
  select(1:3, 6:7, 9:119) %>% 
  #remove participant who did not complete any Q items
  filter(pid != 439)
```

```{r geq}
#group 1

geq1_raw <- d1_raw %>% 
  select(1:35)

geq1_m <- geq1_raw %>% 
  filter(gender == 2) %>% 
  select(1:23, 28:31) %>% 
  rename(gp_1 = q362_1,
         gp_2 = q362_2,
         gp_3 = q362_3,
         gp_4 = q362_4)

geq1_f <- geq1_raw %>% 
  filter(gender == 1) %>% 
  select(1:27) %>% 
  rename(gp_1 = q360_1,
         gp_2 = q360_2,
         gp_3 = q360_3,
         gp_4 = q360_4)

geq1_nb <- geq1_raw %>% 
  filter(gender == 3 | gender == 4 | gender == 5) %>% 
  select(1:23, 32:35) %>% 
  rename(gp_1 = q364_1,
         gp_2 = q364_2,
         gp_3 = q364_3,
         gp_4 = q364_4)

geq1_wide <- bind_rows(geq1_m, geq1_f, geq1_nb)

geq1_long <- geq1_wide %>% 
  rename(sr_1 = q352_1,
         sr_2 = q352_2,
         sr_3 = q352_3,
         sr_4 = q352_4,
         scob_1 = q354_1,
         scob_2 = q354_2,
         scob_3 = q354_3,
         scob_4 = q354_4,
         scob_5 = q354_5,
         inf_1 = q356_1,
         inf_2 = q356_2,
         inf_3 = q356_3,
         wfp_1 = q358_1,
         wfp_2 = q358_2,
         wfp_3 = q358_3,
         wfp_4 = q358_4) %>% 
  gather(item, response, -1:-7) %>% 
  separate(item, c("subscale", "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         subscale = as.factor(subscale),
         scale = "geq") %>% 
  select(1:7, 11, 8:10)

#group 2

geq2_raw <- d2_raw %>% 
  select(1:34)

geq2_m <- geq2_raw %>% 
  filter(gender == 2) %>% 
  select(1:22, 27:30) %>% 
  rename(gp_1 = q70_1,
         gp_2 = q70_2,
         gp_3 = q70_3,
         gp_4 = q70_4)

geq2_f <- geq2_raw %>% 
  filter(gender == 1) %>% 
  select(1:26) %>% 
  rename(gp_1 = q69_1,
         gp_2 = q69_2,
         gp_3 = q69_3,
         gp_4 = q69_4)

geq2_nb <- geq2_raw %>% 
  filter(gender == 3 | gender == 4 | gender == 5) %>% 
  select(1:22, 31:34) %>% 
  rename(gp_1 = q71_1,
         gp_2 = q71_2,
         gp_3 = q71_3,
         gp_4 = q71_4)

geq2_wide <- bind_rows(geq2_m, geq2_f, geq2_nb)

geq2_long <- geq2_wide %>% 
  rename(sr_1 = q65_1,
         sr_2 = q65_2,
         sr_3 = q65_3,
         sr_4 = q65_4,
         scob_1 = q66_1,
         scob_2 = q66_2,
         scob_3 = q66_3,
         scob_4 = q66_4,
         scob_5 = q66_5,
         inf_1 = q67_1,
         inf_2 = q67_2,
         inf_3 = q67_3,
         wfp_1 = q68_1,
         wfp_2 = q68_2,
         wfp_3 = q68_3,
         wfp_4 = q68_4) %>% 
  gather(item, response, -1:-6) %>% 
  separate(item, c("subscale", "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         subscale = as.factor(subscale),
         age = age + 15,
         scale = "geq",
         group = 2) %>% 
  select(1, 11, 2:6, 10, 7:9)

geq_long <- bind_rows(geq1_long, geq2_long)
#write_csv(geq_long, path = "/Users/monikalind/Documents/UO/sap/geq_long.csv")
```

```{r ses}
#group 1

ses1_long <- d1_raw %>% 
  select(1:7, 36:47) %>% 
  mutate(q366_1 = (q366_1 - 1),
         q366_2 = (q366_2 - 1),
         q366_3 = (q366_3 - 1),
         q366_4 = (q366_4 - 1),
         q366_5 = (q366_5 - 1),
         q366_6 = (q366_6 - 1),
         q366_7 = (q366_7 - 1),
         q366_8 = (q366_8 - 1),
         q366_9 = (q366_9 - 1),
         q366_10 = (q366_10 - 1),
         q366_11 = (q366_11 - 1),
         q366_12 = (q366_12 - 1)) %>% 
  gather(item, response, -1:-7) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         scale = "ses") %>% 
  select(1:7, 10, 8:9)

#group 2

ses2_long <- d2_raw %>% 
  select(1:6, 35:46) %>% 
  mutate(q72_1 = (q72_1 - 1),
         q72_2 = (q72_2 - 1),
         q72_3 = (q72_3 - 1),
         q72_4 = (q72_4 - 1),
         q72_5 = (q72_5 - 1),
         q72_6 = (q72_6 - 1),
         q72_7 = (q72_7 - 1),
         q72_8 = (q72_8 - 1),
         q72_9 = (q72_9 - 1),
         q72_10 = (q72_10 - 1),
         q72_11 = (q72_11 - 1),
         q72_12 = (q72_12 - 1)) %>% 
  gather(item, response, -1:-6) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         age = age + 15,
         scale = "ses",
         group = 2) %>% 
  select(1, 10, 2:6, 9, 7:8)

ses_long <- bind_rows(ses1_long, ses2_long)
#write_csv(ses_long, path = "/Users/monikalind/Documents/UO/sap/ses_long.csv")
```

```{r ibqh}
#group 1

ibqh1_long <- d1_raw %>% 
  select(1:7, 48:59) %>% 
  mutate(q368_1 = (q368_1 - 1),
         q368_2 = (q368_2 - 1),
         q368_3 = (q368_3 - 1),
         q368_4 = (q368_4 - 1),
         q368_5 = (q368_5 - 1),
         q368_6 = (q368_6 - 1),
         q368_7 = (q368_7 - 1),
         q368_8 = (q368_8 - 1),
         q368_9 = (q368_9 - 1),
         q368_10 = (q368_10 - 1),
         q368_11 = (q368_11 - 1),
         q368_12 = (q368_12 - 1)) %>% 
  gather(item, response, -1:-7) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         scale = "ibqh") %>% 
  select(1:7, 10, 8:9)

#group 2

ibqh2_long <- d2_raw %>% 
  select(1:6, 47:58) %>% 
  mutate(q73_1 = (q73_1 - 1),
         q73_2 = (q73_2 - 1),
         q73_3 = (q73_3 - 1),
         q73_4 = (q73_4 - 1),
         q73_5 = (q73_5 - 1),
         q73_6 = (q73_6 - 1),
         q73_7 = (q73_7 - 1),
         q73_8 = (q73_8 - 1),
         q73_9 = (q73_9 - 1),
         q73_10 = (q73_10 - 1),
         q73_11 = (q73_11 - 1),
         q73_12 = (q73_12 - 1)) %>% 
  gather(item, response, -1:-6) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         age = age + 15,
         scale = "ibqh",
         group = 2) %>% 
  select(1, 10, 2:6, 9, 7:8)

ibqh_long <- bind_rows(ibqh1_long, ibqh2_long)
#write_csv(ibqh_long, path = "/Users/monikalind/Documents/UO/sap/ibqh_long.csv")
```

```{r ibqa}
#group 1

ibqa1_long <- d1_raw %>% 
  select(1:7, 60:71) %>% 
  mutate(q370_1 = (q370_1 - 1),
         q370_2 = (q370_2 - 1),
         q370_3 = (q370_3 - 1),
         q370_4 = (q370_4 - 1),
         q370_5 = (q370_5 - 1),
         q370_6 = (q370_6 - 1),
         q370_7 = (q370_7 - 1),
         q370_8 = (q370_8 - 1),
         q370_9 = (q370_9 - 1),
         q370_10 = (q370_10 - 1),
         q370_11 = (q370_11 - 1),
         q370_12 = (q370_12 - 1)) %>% 
  gather(item, response, -1:-7) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         scale = "ibqa") %>% 
  select(1:7, 10, 8:9)

#group 2

ibqa2_long <- d2_raw %>% 
  select(1:6, 59:70) %>% 
  mutate(q74_1 = (q74_1 - 1),
         q74_2 = (q74_2 - 1),
         q74_3 = (q74_3 - 1),
         q74_4 = (q74_4 - 1),
         q74_5 = (q74_5 - 1),
         q74_6 = (q74_6 - 1),
         q74_7 = (q74_7 - 1),
         q74_8 = (q74_8 - 1),
         q74_9 = (q74_9 - 1),
         q74_10 = (q74_10 - 1),
         q74_11 = (q74_11 - 1),
         q74_12 = (q74_12 - 1)) %>% 
  gather(item, response, -1:-6) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         age = age + 15,
         scale = "ibqa",
         group = 2) %>% 
  select(1, 10, 2:6, 9, 7:8)

ibqa_long <- bind_rows(ibqa1_long, ibqa2_long)
#write_csv(ibqa_long, path = "/Users/monikalind/Documents/UO/sap/ibqa_long.csv")
```

```{r tsc}
#group 1

tsc1_long <- d1_raw %>% 
  select(1:7, 72:111) %>% 
  mutate(q372_1 = (q372_1 - 1),
         q372_2 = (q372_2 - 1),
         q372_3 = (q372_3 - 1),
         q372_4 = (q372_4 - 1),
         q372_5 = (q372_5 - 1),
         q372_6 = (q372_6 - 1),
         q372_7 = (q372_7 - 1),
         q372_8 = (q372_8 - 1),
         q372_9 = (q372_9 - 1),
         q372_10 = (q372_10 - 1),
         q372_11 = (q372_11 - 1),
         q372_12 = (q372_12 - 1),
         q372_13 = (q372_13 - 1),
         q372_14 = (q372_14 - 1),
         q372_15 = (q372_15 - 1),
         q372_16 = (q372_16 - 1),
         q372_17 = (q372_17 - 1),
         q372_18 = (q372_18 - 1),
         q372_19 = (q372_19 - 1),
         q372_20 = (q372_20 - 1),
         q372_21 = (q372_21 - 1),
         q372_22 = (q372_22 - 1),
         q372_23 = (q372_23 - 1),
         q372_24 = (q372_24 - 1),
         q372_25 = (q372_25 - 1),
         q372_26 = (q372_26 - 1),
         q372_27 = (q372_27 - 1),
         q372_28 = (q372_28 - 1),
         q372_29 = (q372_29 - 1),
         q372_30 = (q372_30 - 1),
         q372_31 = (q372_31 - 1),
         q372_32 = (q372_32 - 1),
         q372_33 = (q372_33 - 1),
         q372_34 = (q372_34 - 1),
         q372_35 = (q372_35 - 1),
         q372_36 = (q372_36 - 1),
         q372_37 = (q372_37 - 1),
         q372_38 = (q372_38 - 1),
         q372_39 = (q372_39 - 1),
         q372_40 = (q372_40 - 1)) %>% 
  gather(item, response, -1:-7) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         scale = "tsc") %>% 
  select(1:7, 10, 8:9)

#group 2

tsc2_long <- d2_raw %>% 
  select(1:6, 71:110) %>% 
  mutate(q75_1 = (q75_1 - 1),
         q75_2 = (q75_2 - 1),
         q75_3 = (q75_3 - 1),
         q75_4 = (q75_4 - 1),
         q75_5 = (q75_5 - 1),
         q75_6 = (q75_6 - 1),
         q75_7 = (q75_7 - 1),
         q75_8 = (q75_8 - 1),
         q75_9 = (q75_9 - 1),
         q75_10 = (q75_10 - 1),
         q75_11 = (q75_11 - 1),
         q75_12 = (q75_12 - 1),
         q75_13 = (q75_13 - 1),
         q75_14 = (q75_14 - 1),
         q75_15 = (q75_15 - 1),
         q75_16 = (q75_16 - 1),
         q75_17 = (q75_17 - 1),
         q75_18 = (q75_18 - 1),
         q75_19 = (q75_19 - 1),
         q75_20 = (q75_20 - 1),
         q75_21 = (q75_21 - 1),
         q75_22 = (q75_22 - 1),
         q75_23 = (q75_23 - 1),
         q75_24 = (q75_24 - 1),
         q75_25 = (q75_25 - 1),
         q75_26 = (q75_26 - 1),
         q75_27 = (q75_27 - 1),
         q75_28 = (q75_28 - 1),
         q75_29 = (q75_29 - 1),
         q75_30 = (q75_30 - 1),
         q75_31 = (q75_31 - 1),
         q75_32 = (q75_32 - 1),
         q75_33 = (q75_33 - 1),
         q75_34 = (q75_34 - 1),
         q75_35 = (q75_35 - 1),
         q75_36 = (q75_36 - 1),
         q75_37 = (q75_37 - 1),
         q75_38 = (q75_38 - 1),
         q75_39 = (q75_39 - 1),
         q75_40 = (q75_40 - 1)) %>% 
  gather(item, response, -1:-6) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         age = age + 15,
         scale = "tsc",
         group = 2) %>% 
  select(1, 10, 2:6, 9, 7:8)

tsc_long <- bind_rows(tsc1_long, tsc2_long)
#write_csv(tsc_long, path = "/Users/monikalind/Documents/UO/sap/tsc_long.csv")
```

```{r bbts}
bbts2_long <- d2_raw %>% 
  select(1:6, 111:116) %>% 
  mutate(q77_1 = (q77_1 - 1),
         q78_2 = (q78_1 - 1),
         q79_3 = (q79_1 - 1),
         q80_4 = (q80_1 - 1),
         q81_5 = (q81_1 - 1),
         q82_6 = (q82_1 - 1)) %>% 
  select(1:7, 13:17) %>% 
  gather(item, response, -1:-6) %>% 
  separate(item, c(NA, "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         age = age + 15,
         scale = "bbts",
         group = 2) %>% 
  select(1, 10, 2:6, 9, 7:8)

#write_csv(bbts2_long, path = "/Users/monikalind/Documents/UO/sap/bbts2_long.csv")
```

```{r create_df}
geq_pid <- geq_long %>% 
  mutate(group = as.factor(group),
         gender = as.factor(gender)) %>% 
  group_by(pid, group, gender) %>% 
  summarise(geq_global = mean(response, na.rm = TRUE)) 

ibqh_pid <- ibqh_long %>% 
  mutate(group = as.factor(group),
         gender = as.factor(gender)) %>% 
  group_by(pid, group, gender) %>% 
  summarise(ibqh_sum = sum(response, na.rm = TRUE))

ibqa_pid <- ibqa_long %>% 
  mutate(group = as.factor(group),
         gender = as.factor(gender)) %>% 
  group_by(pid, group, gender) %>% 
  summarise(ibqa_sum = sum(response, na.rm = TRUE))

tsc_pid <- tsc_long %>% 
  mutate(group = as.factor(group),
         gender = as.factor(gender)) %>% 
  group_by(pid, group, gender) %>% 
  summarise(tsc_sum = sum(response, na.rm = TRUE))

#Joins
geq_ibqh <- left_join(geq_pid, ibqh_pid)
geq_ibqh_tsc <- left_join(geq_ibqh, tsc_pid)
```

```{r models}
#Mean-center IVs
mean_geq <- mean(geq_ibqh_tsc$geq_global, na.rm = TRUE)
mean_ibqh <- mean(geq_ibqh_tsc$ibqh_sum, na.rm = TRUE)

geq_ibqh_tsc <- geq_ibqh_tsc %>% 
  mutate(mc_geq = (geq_global - mean_geq),
         mc_ibqh = (ibqh_sum - mean_ibqh)) 

#write_csv(geq_ibqh_tsc, path = "geq_ibqh_tsc.csv")

#Interaction models
m <- lm(tsc_sum ~ geq_global * ibqh_sum, geq_ibqh_tsc)
mc_m <- lm(tsc_sum ~ mc_geq * mc_ibqh, geq_ibqh_tsc)
summary(lm(tsc_sum ~ geq_global + ibqh_sum, geq_ibqh_tsc))
summary(lm(tsc_sum ~ mc_geq + mc_ibqh, geq_ibqh_tsc))
summary(m)
summary(mc_m)
plot_model(m, type = "int", mdrt.values = "meansd", axis.lim = c(0, 55))

#Create interaction terms (centered and not)
geq_ibqh_tsc$mc_geqXibqh <- geq_ibqh_tsc$mc_geq*geq_ibqh_tsc$mc_ibqh
geq_ibqh_tsc$geqXibqh <- geq_ibqh_tsc$geq_global*geq_ibqh_tsc$ibqh_sum

#Create dfs for 3 IVs - centered and not
regressors <- geq_ibqh_tsc[c(4,5,9)]
mc_regressors <- geq_ibqh_tsc[c(7,8,10)]

#Mean-centering worked partially
corr.test(regressors)
corr.test(mc_regressors)

# Test for skewness
library(e1071)
skewness(regressors$geq_global)
skewness(regressors$ibqh_sum)

# Test residuals as predictor
# Save residuals from regressing betrayal on harassment
lm_ibqh_by_geq <- lm(mc_ibqh ~ mc_geq, geq_ibqh_tsc)
geq_ibqh_tsc$resids_ibqh_by_geq <- lm_ibqh_by_geq$residuals

# Save residuals from regressing harassment on betrayal
lm_geq_by_ibqh <- lm(mc_geq ~ mc_ibqh, geq_ibqh_tsc)
geq_ibqh_tsc$resids_geq_by_ibqh <- lm_geq_by_ibqh$residuals

# Regress trauma sx on harassment and residuals from regressing betrayal on harassment
summary(lm(tsc_sum ~ mc_geq + resids_ibqh_by_geq, geq_ibqh_tsc))

# The weird person is not driving the effect of residuals [-4,105]
plot(tsc_sum~resids_ibqh_by_geq,geq_ibqh_tsc)
```

```{r no_trolls}
no_trolls <- geq_ibqh_tsc %>% 
  filter(pid != 65)

no_trolls_fm <- no_trolls %>% 
  filter(gender == 1 | gender == 2)

# Multiple regression, no interaction term
summary(lm(tsc_sum ~ gender + mc_geq + mc_ibqh, no_trolls))

# Multiple regression, with interaction term
summary(lm(tsc_sum ~ gender + mc_geq * mc_ibqh, no_trolls))

# Trauma sx by gender harassment
summary(lm(tsc_sum ~ mc_geq, no_trolls))

# Trauma sx by harassment and residuals of regressing betrayal on harassment
summary(lm(tsc_sum ~ mc_geq + resids_ibqh_by_geq, no_trolls))

# Trauma sx by residuals of regressing betrayal on harassment
summary(lm(tsc_sum ~ resids_ibqh_by_geq, no_trolls))

# Trauma sx by betrayal
summary(lm(tsc_sum ~ mc_ibqh, no_trolls))

# Trauma sx by betrayal and residuals of regressing harassment on betrayal
summary(lm(tsc_sum ~ mc_ibqh + resids_geq_by_ibqh, no_trolls))

# Nick's residuals way
# Regress trauma sx on harassment
lm_tsc_by_geq <- lm(tsc_sum ~ mc_geq, no_trolls)
# Save residuals
no_trolls$resids_tsc_by_geq <- lm_tsc_by_geq$residuals

# Residuals of regressing trauma sx on harassment by betrayal
summary(lm(resids_tsc_by_geq ~ mc_ibqh, no_trolls))
```

```{r women_only}
# Women only
women_only <- geq_ibqh_tsc %>% 
  filter(gender == 1)

summary(lm(tsc_sum ~ mc_geq, women_only))
summary(lm(tsc_sum ~ mc_geq + resids_ibqh_by_geq, women_only))
summary(lm(tsc_sum ~ mc_ibqh, women_only))
summary(lm(tsc_sum ~ mc_ibqh + resids_geq_by_ibqh, women_only))

# Men only
men_only <- geq_ibqh_tsc %>% 
  filter(gender == 2)

summary(lm(tsc_sum ~ mc_geq, men_only))
summary(lm(tsc_sum ~ mc_geq + resids_ibqh_by_geq, men_only))
summary(lm(tsc_sum ~ mc_ibqh, men_only))
summary(lm(tsc_sum ~ mc_ibqh + resids_geq_by_ibqh, men_only))
```

```{r basic_plots}
#GEQ by gender density plot
no_trolls %>% 
  filter(gender == 1 | gender == 2) %>% 
  ggplot(aes(geq_global, fill = gender)) +
  geom_density(alpha = .7)

#IBQ-H by gender density plot
no_trolls %>% 
  filter(gender == 1 | gender == 2) %>% 
  ggplot(aes(ibqh_sum, fill = gender)) +
  geom_density(alpha = .7)

#IBQ-A by gender density plot
ibqa_pid %>% 
  filter(gender == 1 | gender == 2,
         pid != 65) %>% 
  ggplot(aes(ibqa_sum, fill = gender)) +
  geom_density(alpha = .7)

#IBQ-H by GEQ scatter plot
ggplot(no_trolls, aes(geq_global, ibqh_sum)) +
  geom_point(aes(color = gender)) +
  geom_smooth(method = "lm") +
  scale_color_OkabeIto()

#TSC by GEQ scatter plot
ggplot(no_trolls, aes(geq_global, tsc_sum)) +
  geom_point() +
  geom_smooth(method = "lm")

#TSC by IBQ-H scatter plot
ggplot(no_trolls, aes(ibqh_sum, tsc_sum)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r item_level_summaries}
ibqh_long %>% 
  mutate(item = as.numeric(item)) %>% 
  filter(gender == 1 | gender == 2) %>% 
  group_by(item, gender) %>% 
  summarize(mean = mean(response, na.rm = TRUE),
            sd = sd(response, na.rm = TRUE)) %>% 
  ggplot(aes(item, mean, color = gender)) +
  geom_point()

geq_long %>% 
  mutate(item = as.numeric(item)) %>% 
  filter(gender == 1 | gender == 2) %>% 
  group_by(item, subscale, gender) %>% 
  summarize(mean = mean(response, na.rm = TRUE),
            sd = sd(response, na.rm = TRUE))  %>% 
  arrange(subscale, item)

ibqa_long %>% 
  mutate(item = as.numeric(item)) %>% 
  filter(gender == 1 | gender == 2) %>% 
  group_by(item, gender) %>% 
  summarize(mean = mean(response, na.rm = TRUE),
            sd = sd(response, na.rm = TRUE))

ses_long %>% 
  mutate(item = as.numeric(item)) %>% 
  filter(gender == 1 | gender == 2) %>% 
  group_by(item, gender) %>% 
  summarize(mean = mean(response, na.rm = TRUE),
            sd = sd(response, na.rm = TRUE))

tsc_long %>% 
  mutate(item = as.numeric(item)) %>% 
  group_by(item) %>% 
  summarize(mean = mean(response, na.rm = TRUE),
            sd = sd(response, na.rm = TRUE)) %>% 
  arrange(mean)
```



